<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Caixa.Core\Caixa.Core.csproj" />
    <PackageReference Include="PDFsharp-MigraDoc-GDI" Version="6.2.4" />
  </ItemGroup>
</Project>
